# keybinds.conf - Hyprland Keybindings

$mod = SUPER

# Uygulama Başlatıcı
bind = $mod, RETURN, exec, kitty
bind = $mod, D, exec, dolphin

# Sistem
bind = $mod SHIFT, Q, exit,
bind = $mod, E, exec, pavucontrol
bind = $mod, P, exec, wlogout

# Pencere Yönetimi
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

bind = $mod, F, fullscreen,
bind = $mod, SPACE, togglefloating,

# Workspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Scratchpad
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

# Ekran Kilidi
bind = $mod, L, exec, hyprlock

# Ekran Görüntüsü
bind = $mod SHIFT, S, exec, grimblast --notify copysave area
bind = $mod SHIFT, P, exec, grimblast --notify copysave output
bind = $mod SHIFT, O, exec, grimblast --notify copysave window
