# windowrules.conf - Hyprland Pencere Kuralları

# Tam ekran başlasın
windowrule = fullscreen, ^(mpv)$

# Floating başlasın
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(blueman-manager)$
windowrule = float, ^(org.gnome.Calculator)$

# Always on top
windowrule = stayfocused, ^(com.bitwarden.desktop)$

# Borderless
windowrule = noborder, ^(dunst)$

# Boyut & pozisyon (örnek)
# windowrulev2 = size 800 600, class:^(Vesktop)$
# windowrulev2 = move 50 50, class:^(Vesktop)$
